require 'claide'

module CocoaBean
  class Command < CLAide::Command
    require 'cocoa_bean/command/new'
    require 'cocoa_bean/command/preview'
    require 'cocoa_bean/command/about'
    require 'cocoa_bean/command/test'
    require 'cocoa_bean/command/open'

    self.abstract_command = true
    self.command = 'cocoabean'
    self.version = VERSION
    self.description = <<DESC
CocoaBean is a javaScript application framework. The application can be
generated by 'cocoabean new' command. A cocoa bean application can be
generated into 'html app', 'iOS app' and 'OS X app' with one command. Android
and windows will be supported in the future.

Inside a cocoa bean application, use 'cocoabean test' to unit test your code.
use 'cocoabean preview' to launch web browser or simulator depends on options
you provided and application configuration. Use 'cocoabean open' to open the
application in your favorite text editor or IDE. Use 'cocoabean dist' to
generate the application executable or web page.

You may customize the behavior of CocoaBean through 'Beanfile' and '~/.cocoabeanrc'.

If you find any bugs or if you have feature request, welcome to fire an issue here 'https://github.com/cheunghy/CocoaBean/issues'.

Thanks for downloading and using CocoaBean.
DESC
  end
end
